services:
  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails
      - sqlite_data:/rails/db/sqlite
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    networks:
      - network

volumes:
  sqlite_data:

networks:
  network:
